// swift-tools-version:5.9
import PackageDescription

// Loom — local-LLM-powered fiction writing app for macOS.
// Phase 1 ships a minimal Swift Package: LoomCore (library), Loom (app),
// LoomCoreTests (TestKit harness). Future phases may add smoke runners
// matching RPClient's per-surface harness pattern.
//
// macOS 14 minimum matches RPClient. The user's reference platform is
// macOS 26 Tahoe / Liquid Glass; the floor is set by the Swift toolchain
// available on the user's CLT install, not by AppKit features used.
let package = Package(
    name: "Loom",
    platforms: [.macOS(.v14)],
    // huggingface/swift-transformers 1.0 (2025-09-26) gives us the
    // RoBERTa BPE tokenizer in pure Swift so the Wegmann CoreML
    // bundle can be driven without a Python subprocess. macOS 13+;
    // we're on 14. Tokenizers product only — skips the Generation /
    // Models products that would drag CoreML build steps in.
    dependencies: [
        .package(url: "https://github.com/huggingface/swift-transformers", from: "1.0.0"),
        // ONNX Runtime — drives the GLiNER native entity detector.
        // GLiNER's DeBERTa-v3 backbone won't trace through coremltools
        // (verified), so this is the native inference path. Zero
        // runtime Python; the model is exported offline by
        // Tools/GLiNERProbe/export_gliner_onnx.py.
        .package(url: "https://github.com/microsoft/onnxruntime-swift-package-manager", from: "1.24.2"),
    ],
    targets: [
        .executableTarget(
            name: "Loom",
            dependencies: ["LoomCore"],
            path: "Sources/Loom"
        ),
        .target(
            name: "LoomCore",
            dependencies: [
                .product(name: "Tokenizers", package: "swift-transformers"),
                .product(name: "onnxruntime", package: "onnxruntime-swift-package-manager"),
            ],
            path: "Sources/LoomCore",
            // Bundle the Bible Workspace WKWebView assets (Vite/React
            // build output) and the Wegmann CoreML inference bundle.
            // Both directories are gitignored — regenerated locally
            // before `swift build` by:
            //   scripts/build-bible-workspace.sh
            //   Tools/CoreMLProbe/build_mlpackage.py
            // See LOOM_BIBLE_WORKSPACE.md §5.5 +
            // Tools/CoreMLProbe/build_mlpackage.py.
            resources: [
                .copy("Resources/BibleWorkspace"),
                // Planned Project wizard — separate webview bundle,
                // gitignored, populated by scripts/build-bible-workspace.sh.
                .copy("Resources/PlannedProject"),
                // Project-tools webview (scene framing + anti-slop) —
                // separate bundle, gitignored, built by the same script.
                .copy("Resources/ProjectTools"),
                .copy("Resources/StyleEmbedding"),
                // GLiNER ONNX bundle — gitignored, regenerated by
                // Tools/GLiNERProbe/export_gliner_onnx.py before build.
                .copy("Resources/GLiNER"),
                // NLI cross-encoder ONNX bundle — gitignored, regenerated
                // by Tools/NLIProbe/export_nli_onnx.py before build.
                .copy("Resources/NLI"),
            ],
            swiftSettings: [
                // Enables `@testable import LoomCore` from the test runner
                // in debug builds. Scoped to debug so release (.app) is
                // unaffected.
                .unsafeFlags(["-enable-testing"], .when(configuration: .debug)),
            ]
        ),
        .executableTarget(
            name: "LoomCoreTests",
            dependencies: ["LoomCore"],
            path: "Tests/LoomCoreTests",
            // Bundle the fixture JSON so the eval runner (LedgerSpike,
            // declared below) can resolve `Bundle.module` to read it.
            // The LedgerSpike target imports LoomCore for the
            // extraction module and re-reads the fixture from disk.
            exclude: ["Fixtures"]
        ),
        // One-off network-y eval runners ("spike" targets). These hit
        // a live local-LLM server and emit a markdown report; they're
        // not part of the standard test suite. Run on demand:
        //   `swift run LedgerSpike` (requires the Qwen3.6-27B
        //   summariser-role server reachable at the configured URL).
        .executableTarget(
            name: "LedgerSpike",
            dependencies: ["LoomCore"],
            path: "Tools/LedgerSpike"
        ),
        // Phase 9 entity-discovery spike runner
        // (LOOM_ENTITY_DISCOVERY_SPIKE.md §6.3). Reads the fixture,
        // drives Stage A2 (candidate gen) + B (gate) + D
        // (normalisation) against Ollama, scores vs gold, emits a
        // markdown report. Run: `swift run EntityDiscoverySpike`
        // (requires gemma4_2b at LOOM_SPIKE_OLLAMA_URL,
        //  default http://localhost:11434/).
        .executableTarget(
            name: "EntityDiscoverySpike",
            dependencies: ["LoomCore"],
            path: "Tools/EntityDiscoverySpike"
        ),
        // Phase 5 RAG-for-style spike runner (LOOM_RAG_SPIKE.md §6).
        // Reads the fixture, hits Kobold + Ollama for Paths A/B/C,
        // and consumes the Python sidecar's vectors.json for Paths
        // D + E. Run with `swift run RagSpike --smoke`.
        .executableTarget(
            name: "RagSpike",
            dependencies: ["LoomCore"],
            path: "Tools/RagSpike",
            exclude: ["Python"]
        ),
        // Phase 7.a Scene-Template Generation spike runner
        // (LOOM_SCENE_TEMPLATE.md §9). Reads fixtures, hits the Ollama
        // gemma4_2b extractor for Pass A beat extraction, and emits
        // Markdown reports for hand-grading. Run with:
        //   swift run SceneTemplateSpike --extract <fixture.md>
        //   swift run SceneTemplateSpike --extract-all
        .executableTarget(
            name: "SceneTemplateSpike",
            dependencies: ["LoomCore"],
            path: "Tools/SceneTemplateSpike",
            exclude: ["Fixtures", "last-run"]
        ),
        // Phase 8.a §6.1 embedder discrimination spike runner
        // (LOOM_SCENE_EXEMPLAR.md §6.1 + LOOM_SCENE_EXEMPLAR_RESEARCH.md).
        // Loads the 20-fixture register/style set, embeds each fixture
        // with each candidate embedder (StyleDistance / Wegmann / LUAR /
        // mxbai), and emits a per-embedder cosine matrix + separation
        // score to LOOM_SCENE_EXEMPLAR_SPIKE.md.
        //   swift run SceneExemplarSpike cosine-matrix --embedder=<id>
        .executableTarget(
            name: "SceneExemplarSpike",
            dependencies: ["LoomCore"],
            path: "Tools/SceneExemplarSpike",
            exclude: ["fixtures", "last-run"]
        ),
        // HANDOFF §15.27 relationship-discovery precision probe.
        // Drives the two-stage pairwise classifier against Ollama and
        // compares self-consistency voting (rounds 3) to the un-voted
        // baseline (rounds 1) on test2 Scene 2.
        //   swift run RelationshipDiscoveryProbe
        .executableTarget(
            name: "RelationshipDiscoveryProbe",
            dependencies: ["LoomCore"],
            path: "Tools/RelationshipDiscoveryProbe"
        ),
        // GLiNER entity-detection probe — runs the detector on a scene
        // file at a low threshold and prints every span's sigmoid
        // score, for diagnosing missed entities.
        //   swift run EntityDetectionProbe <scene.md>
        .executableTarget(
            name: "EntityDetectionProbe",
            dependencies: ["LoomCore"],
            path: "Tools/EntityDetectionProbe"
        ),
        // LOOM_PLANNED_PROJECT Phase 2 — outline-generation probe.
        // Runs OutlineGenerator against Ollama and prints the
        // resulting manuscript outline, for tuning the prompts.
        //   swift run OutlineGenerationProbe
        .executableTarget(
            name: "OutlineGenerationProbe",
            dependencies: ["LoomCore"],
            path: "Tools/OutlineGenerationProbe"
        ),
        // Planned Project Phase 5 — runs OutlineDraftCoordinator
        // against the live writer model and prints the drafted scene
        // prose, for tuning the beat-plan + per-beat draft prompts.
        //   swift run OutlineDraftProbe
        .executableTarget(
            name: "OutlineDraftProbe",
            dependencies: ["LoomCore"],
            path: "Tools/OutlineDraftProbe"
        ),
        // Continuity Audit (L10) Phase A feasibility spike. Drives the
        // ContinuityAuditSpike fixture through per-scene typed-claim
        // extraction and pairwise adjudication against the live local
        // models, and scores both against the hand-graded gold set.
        //   swift run ContinuityAuditSpike
        .executableTarget(
            name: "ContinuityAuditSpike",
            dependencies: ["LoomCore"],
            path: "Tools/ContinuityAuditSpike"
        ),
    ]
)
