import Foundation
@testable import LoomCore

/// GLiNER native entity detector — phase 3 tokenizer parity.
///
/// The load-bearing check: swift-transformers' Unigram path must
/// tokenize byte-for-byte identically to the Python DeBERTa-v3
/// tokenizer the ONNX model was trained against. Mismatched token ids
/// would silently corrupt every inference. The fixture is generated by
/// `Tools/GLiNERProbe/dump_tokenizer_fixture.py`.
func glinerTokenizerTests() -> TestSuite {
    let s = TestSuite("GLiNERTokenizer")

    struct Fixture: Decodable {
        struct Case: Decodable {
            let text: String
            let ids: [Int]
        }
        let cases: [Case]
    }

    s.test("encodes probe strings identically to the Python DeBERTa tokenizer") {
        let fixtureURL = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .appendingPathComponent("Fixtures/gliner_tokenizer_fixture.json")
        let fixtureData = try expectNotNil(
            try? Data(contentsOf: fixtureURL),
            file: #file, line: #line
        )
        let fixture = try JSONDecoder().decode(Fixture.self, from: fixtureData)
        try expectGreaterThan(fixture.cases.count, 0)

        let tokenizer: GLiNERTokenizer
        do {
            tokenizer = try awaitSync { try await GLiNERTokenizer() }
        } catch GLiNERRuntime.RuntimeError.modelBundleMissing {
            // The GLiNER bundle is gitignored + regenerated locally;
            // skip when it hasn't been exported.
            return
        }

        for c in fixture.cases {
            let got = tokenizer.encode(c.text)
            try expectEqual(got, c.ids, "token mismatch for \(c.text.debugDescription)")
        }
    }

    return s
}

/// Run an async operation from a synchronous (TestKit) context. The
/// work runs on a detached task off the MainActor, so blocking the
/// caller on the semaphore cannot deadlock.
private func awaitSync<T>(_ body: @escaping @Sendable () async throws -> T) throws -> T {
    let semaphore = DispatchSemaphore(value: 0)
    let box = ResultBox<T>()
    Task.detached {
        do { box.value = .success(try await body()) }
        catch { box.value = .failure(error) }
        semaphore.signal()
    }
    semaphore.wait()
    switch box.value {
    case .success(let v): return v
    case .failure(let e): throw e
    case .none: throw TestFailure(message: "awaitSync produced no result", file: #file, line: #line)
    }
}

private final class ResultBox<T>: @unchecked Sendable {
    var value: Result<T, Error>?
}
