import Foundation

let suites: [TestSuite] = [
    phase1DebugLogTests(),
    phase1ProjectCodableTests(),
    phase1SceneFrontmatterTests(),
    phase1ProjectStorageTests(),
    phase1SchemaVersionTests(),
    phase1ServerProbeParseTests(),
    phase1KoboldClientRegistryTests(),
    phase1AppSettingsCodableTests(),
    phase1KoboldClientSmokeTests(),
    phase1DesignTokensTests(),
    phase1SceneListOperationsTests(),
    phase1ProjectSessionTests(),
    phase1SidebarMountTests(),
    phase1EditorWordCountTests(),
    phase1ProjectSessionSelectionTests(),
    phase1CharacterAddTests(),
    phase1InspectorTabPersistenceTests(),
    phase1GenerationModeAvailabilityTests(),
    phase1InstructTemplateTests(),
    phase1RecentProseWindowTests(),
    phase1PromptBuilderLayersTests(),
    phase1PersistedSessionTests(),
    phase1AcceptanceStateTests(),
    phase1HistoryLogReadWriteTests(),
    phase1HistoryExpansionTests(),
    phase1MarkdownExportTests(),
    phase1RefusalDetectionTests(),
    phase1EmptyStateTests(),
    phase1RecentProjectsTests(),
    phase1ProjectCorruptionTests(),
    phase1ThinkBlockStripperTests(),
    phase1AuthorsNoteInjectorTests(),
    phase2AppSettingsMutationsTests(),
    phase2ProjectSettingsMutationsTests(),
    phase2SettingsControllerMountTests(),
    phase2RecommendedContextBudgetTests(),
    phase2WritingDirectionTests(),
    phase2FanficMetadataTests(),
    phase2CharacterSchemaTests(),
    phase2BibleEntitiesTests(),
    phase2BibleEntityMutationsTests(),
    phase2BibleViewModelTests(),
    phase2BibleInspectorMountTests(),
    phase2NarrativeStyleTests(),
    phase2ProjectSettingsPickersTests(),
    phase2InjectionModeTests(),
    phase2BibleInjectorTests(),
    phase2BibleKeyedIntegrationTests(),
    phase2InjectionModePillTests(),
    phase2LorebookSchemaTests(),
    phase2LorebookIntegrationTests(),
    phase2SnapshotsTests(),
    phase2SnapshotOnRewriteTests(),
    phase2EntityAutocompleteTests(),
    phase2EntityReferenceTests(),
    phase2MentionContextTests(),
    phase2EditorMentionTests(),
    phase2MentionIndexTests(),
    phase2MentionDisplayTests(),
    phase2KeepAndRedoShortcutTests(),
    phase2CancelShortcutTests(),
    phase2AutoProbeTests(),
    phase2MentionPopoverTests(),
    phase2SparklineLayoutTests(),
    phase2SparklineViewTests(),
    phase2SparklineWiringTests(),
    phase2EntityReferenceRangesTests(),
    phase2EntityHoverTests(),
]

// `TestRunner.run` is `@MainActor`-isolated so test bodies can drive
// MainActor-bound types. Top-level main.swift code isn't actor-isolated
// by default, but executables run their main on the main thread, so
// `assumeIsolated` is the right hop.
exit(MainActor.assumeIsolated { TestRunner.run(suites) })
