import Foundation
@testable import LoomCore

/// Continuity Audit NLI gate — cross-encoder tests.
///
/// The load-bearing check: Swift's pair tokenisation
/// (`[CLS] A [SEP] B [SEP]`) must match Python's tokenizer
/// byte-for-byte — otherwise the model's logits drift. The fixture is
/// generated by `Tools/NLIProbe/dump_tokenizer_fixture.py`.
func nliCrossEncoderTests() -> TestSuite {
    let s = TestSuite("NLICrossEncoder")

    struct Fixture: Decodable {
        struct Case: Decodable {
            let premise: String
            let hypothesis: String
            let input_ids: [Int]
            let attention_mask: [Int]
        }
        let cases: [Case]
    }

    func loadCrossEncoder() throws -> NLICrossEncoder? {
        let env = try NLIRuntime.makeEnvironment()
        do {
            return try awaitSync { try await NLICrossEncoder(env: env) }
        } catch NLIRuntime.RuntimeError.modelBundleMissing {
            // The NLI bundle is gitignored + regenerated locally; skip
            // when it hasn't been exported.
            return nil
        }
    }

    s.test("encodePair matches Python's pair tokenisation byte-for-byte") {
        let fixtureURL = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .appendingPathComponent("Fixtures/NLI/tokenizer_fixture.json")
        guard let data = try? Data(contentsOf: fixtureURL) else {
            // Fixture is generated alongside the model bundle — skip
            // when neither is present.
            return
        }
        let fixture = try JSONDecoder().decode(Fixture.self, from: data)
        try expectGreaterThan(fixture.cases.count, 0)

        guard let nli = try loadCrossEncoder() else { return }

        for c in fixture.cases {
            let (ids, mask) = nli.encodePair(premise: c.premise, hypothesis: c.hypothesis)
            try expectEqual(
                ids, c.input_ids,
                "input_ids mismatch for \(c.premise.debugDescription) / \(c.hypothesis.debugDescription)")
            try expectEqual(
                mask, c.attention_mask,
                "attention_mask mismatch for \(c.premise.debugDescription) / \(c.hypothesis.debugDescription)")
        }
    }

    s.test("scores a clear contradiction as `contradiction`") {
        guard let nli = try loadCrossEncoder() else { return }
        let r = try nli.score(
            premise: "the vault is on the fourteenth floor",
            hypothesis: "the vault is on the ninth floor")
        try expectEqual(r.label, .contradiction)
    }

    s.test("scores genuinely unrelated claims as `neutral`") {
        guard let nli = try loadCrossEncoder() else { return }
        let r = try nli.score(
            premise: "the lighthouse is north of the village",
            hypothesis: "Mara has green eyes")
        try expectEqual(r.label, .neutral)
    }

    s.test("shouldKeep drops only confident-neutral pairs (P(neutral) ≥ neutralMax)") {
        let confidentNeutral = NLICrossEncoder.Result(
            label: .neutral,
            probs: [.contradiction: 0.04, .entailment: 0.03, .neutral: 0.93])
        let borderlineNeutral = NLICrossEncoder.Result(
            label: .neutral,
            probs: [.contradiction: 0.42, .entailment: 0.05, .neutral: 0.53])
        let clearContradiction = NLICrossEncoder.Result(
            label: .contradiction,
            probs: [.contradiction: 0.95, .entailment: 0.01, .neutral: 0.04])

        // Default 0.7: drop confident neutrals; keep borderline + clear matches.
        try expectFalse(NLICrossEncoder.shouldKeep(confidentNeutral))
        try expectTrue(NLICrossEncoder.shouldKeep(borderlineNeutral))
        try expectTrue(NLICrossEncoder.shouldKeep(clearContradiction))
    }

    s.test("softmax probabilities sum to 1 across the three labels") {
        guard let nli = try loadCrossEncoder() else { return }
        let r = try nli.score(premise: "the King died", hypothesis: "the King is alive")
        let total = NLICrossEncoder.Label.allCases.reduce(Float(0)) { $0 + (r.probs[$1] ?? 0) }
        try expectLessThan(abs(total - 1.0), Float(0.001))
    }

    return s
}
