import Foundation
@testable import LoomCore

// Phase 8.c — integration test for CoreMLEmbeddingClient driving the
// bundled Wegmann `.mlpackage` via Apple's CoreML framework. Loads
// the real bundle + tokenizer (no mocks), runs two embeds, asserts:
//
//   1. The bundle resolves via Bundle.module (resource wiring works).
//   2. Output is 768-dim and L2-normalised within a tolerance
//      (consistent with the build script baking the L2-norm in).
//   3. Same input → byte-identical output (no per-call randomness).
//   4. Different inputs → different outputs (the client isn't a
//      degenerate constant).
//
// Skips with a logged warning if the bundle isn't present — the
// test target depends on LoomCore, and LoomCore's
// Resources/StyleEmbedding is gitignored + regenerated by
// Tools/CoreMLProbe/build_mlpackage.py before swift build. A fresh
// clone that hasn't run the build script should still pass the suite.

func phase8cCoreMLEmbeddingClientTests() -> TestSuite {
    let s = TestSuite("Phase8cCoreMLEmbeddingClient")

    s.test("defaultBundleURL resolves; client embeds a 768-dim L2-normalised vector") {
        guard let bundleURL = CoreMLEmbeddingClient.defaultBundleURL() else {
            // Bundle is missing — local-bootstrap state. Log + skip
            // so a fresh clone before build_mlpackage.py runs doesn't
            // fail the suite.
            print("[skip] StyleEmbedding bundle not present at Bundle.module — run Tools/CoreMLProbe/build_mlpackage.py")
            return
        }
        let client = CoreMLEmbeddingClient(bundleURL: bundleURL)

        let v = try expectNotNil(client.embed("She walked the road. The road was long."))
        try expectEqual(v.dim, 768)

        // L2-norm should be ~1.0 (the mlpackage bakes the
        // normalisation in). Allow a small tolerance for FP16
        // accumulation.
        var sumSquares: Float = 0
        for x in v.values { sumSquares += x * x }
        let norm = sqrt(sumSquares)
        try expectTrue(abs(norm - 1.0) < 0.01,
                       "expected L2 norm ≈ 1.0, got \(norm)")

        // Sanity: not the all-zero degenerate case.
        let maxAbs = v.values.map { abs($0) }.max() ?? 0
        try expectTrue(maxAbs > 0.001, "vector is degenerate")
    }

    s.test("same input produces identical vectors (deterministic)") {
        guard let bundleURL = CoreMLEmbeddingClient.defaultBundleURL() else { return }
        let client = CoreMLEmbeddingClient(bundleURL: bundleURL)
        let text = "Determinism check."
        guard let a = client.embed(text), let b = client.embed(text) else {
            throw TestFailure(message: "embed returned nil", file: #file, line: #line)
        }
        // Float-equal vector comparison; CoreML is deterministic for
        // the same input on the same compute units.
        try expectEqual(a.dim, b.dim)
        for i in 0..<a.dim {
            try expectTrue(a.values[i] == b.values[i],
                           "drift at index \(i): \(a.values[i]) vs \(b.values[i])")
        }
    }

    s.test("different inputs produce different vectors (non-degenerate)") {
        guard let bundleURL = CoreMLEmbeddingClient.defaultBundleURL() else { return }
        let client = CoreMLEmbeddingClient(bundleURL: bundleURL)
        guard let a = client.embed("She walked the road."),
              let b = client.embed("The corridors stretched away in shadow.") else {
            throw TestFailure(message: "embed returned nil", file: #file, line: #line)
        }
        let cos = EmbeddingVector.cosine(a, b)
        // Two real (different) sentences should have cosine < 1.0 by a
        // healthy margin. 0.95 is a generous floor that catches the
        // "client returns a constant vector" failure mode.
        try expectLessThan(cos, 0.95)
        try expectGreaterThan(cos, -1.0)
    }

    return s
}
